language: node_js
node_js:
  - "8.9.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - cp env.example.js env.js
  - npm run lint
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode10
      node_js: false
      before_install:
        - nvm install 8
        - node --version
        - travis_retry yarn install
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
        - yarn add react-native-cli
      script:
        - cd ios
        - bundle install
        - bundle exec pod install
        - bundle exec fastlane test_build_only
