language: node_js
node_js:
  - "8.9.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - cp env.example.js env.js
  - npm run lint
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode10
      node_js: false
      before_install:
        - nvm install 8
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      script:
        - cd ios
        - bundle install
        - gem install fastlane --no-rdoc --no-ri --no-document --quiet
        - bundle exec pod install
        - cd ../node_modules/react-native/scripts
        - ./ios-install-third-party.sh
        - cd third-party/glog-0.3.5
        - ../../scripts/ios-configure-glog.sh
        - cd ios
        - bundle exec fastlane test
