language: node_js
node_js:
- 8.9.1
sudo: false
cache:
  directories:
  - "$HOME/.yarn-cache"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cp env.example.js env.js
- npm run lint
- npm test
- npm run bundle:ios
matrix:
  include:
  - language: objective-c
    os: osx
    osx_image: xcode10
    node_js: false
    before_install:
    - openssl aes-256-cbc -K $encrypted_8a62bc148fe6_key -iv $encrypted_8a62bc148fe6_iv
      -in bitbucket_swadeshness.enc -out ~\/.ssh/bitbucket_swadeshness -d
    - nvm install 8
    - node --version
    - travis_retry npm install -g yarn
    - yarn -version
    install:
    - travis_retry gem install xcpretty
    - travis_retry yarn
    script:
    - echo -e "Host bitbucket.org\n\tHostName bitbucket.org\n\tUser git\n\tIdentityFile
      ~/.ssh/bitbucket_swadeshness\n" >> ~/.ssh/config
    - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/bitbucket_swadeshness
    - cd ios
    - bundle install
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet
    - bundle exec pod install
    - cd ../node_modules/react-native/scripts
    - "./ios-install-third-party.sh"
    - cd third-party/glog-0.3.5
    - pwd && ../../ios-configure-glog.sh
    - pwd && cd ../../../../../ios
    - bundle exec fastlane test
before_install:
- openssl aes-256-cbc -K $encrypted_8a62bc148fe6_key -iv $encrypted_8a62bc148fe6_iv
  -in bitbucket_swadeshness.enc -out ~\/.ssh/bitbucket_swadeshness -d
