language: node_js
node_js:
  - "8.9.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - cp env.example.js env.js
  - npm run lint
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode10
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/SwadeshNessMobile.xcodeproj
      xcode_scheme: ios/SwadeshNessMobileTests
      script:
        - cd ios
        - xcodebuild -scheme SwadeshNessMobile -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme SwadeshNessMobile -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
