# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane"
gem "json"
gem 'cocoapods', '1.7.0.beta.3'
gem "xcode-install"
