# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwadeshNessMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
#  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  # Pods for SwadeshNessMobile

#  target 'SwadeshNessMobile-tvOSTests' do
#   inherit! :search_paths
#  end

  target 'SwadeshNessMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SwadeshNessMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwadeshNessMobile-tvOS

  target 'SwadeshNessMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
