default_platform(:ios)

def ci_setup_keychain
  create_keychain(
    name: ENV["MATCH_KEYCHAIN_NAME"],
    password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  unlock_keychain(
    path: ENV["MATCH_KEYCHAIN_NAME"],
    add_to_search_list: :replace,
    password: ENV['MATCH_KEYCHAIN_PASSWORD']
  )
end

def setup_codesigning
  match(
      app_identifier: "jp.ivan.SwadeshNessMobile",
      type: "appstore",
      readonly: true
    )
end

def build_sign
  gym(
    scheme: "SwadeshNessMobile",
    clean: true,
    export_method: "app-store"
  )
end

def test
  scan(
    scheme: "SwadeshNessMobile"
  )
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "SwadeshNessMobile.xcodeproj")
    sh("git status")
    push_to_git_remote
    ci_setup_keychain
    setup_codesigning
    test
    build_sign
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  lane :buildtest do
    ci_setup_keychain
    setup_codesigning
    test
    build_sign
  end  
  
  lane :localbuild do
    swadeshness_match
    build_sign
  end
end
