# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def perform_sign
    #create_keychain(
    #  name: ENV["MATCH_KEYCHAIN_NAME"],
    #  password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    #  default_keychain: true,
    #  unlock: true,
    #  timeout: 3600,
    #  add_to_search_list: true
    #)

    #unlock_keychain(
    #  path: ENV["MATCH_KEYCHAIN_NAME"],
    #  add_to_search_list: :replace,
    #  password: ENV['MATCH_KEYCHAIN_PASSWORD']
    #)
    match(
      app_identifier: "jp.ivan.SwadeshNessMobile",
      type: "appstore"
    )
end



platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "SwadeshNessMobile.xcodeproj")
    build_app(scheme: "SwadeshNessMobile")
    upload_to_testflight
  end

  lane :build do
    xcversion(version: "9.4.1")
    perform_sign
    gym(
      scheme: "SwadeshNessMobile",
      #workspace: "./SwadeshNessMobile.xcworkspace", # since using pods
      #export_method: "app-store",
      #configuration: "Release",
      clean: "true",
      export_options: {
        provisioningProfiles: { 
            "jp.ivan.SwadeshNessMobile" => "match AppStore jp.ivan.SwadeshNessMobile"
        }
      }
    )
  end

  lane :test do 
        #scan(
    #  scheme: "SwadeshNessMobile"
    #)
  end
end
