# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "SwadeshNessMobile.xcodeproj")
    build_app(scheme: "SwadeshNessMobile")
    upload_to_testflight
  end

  lane :test do 
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    unlock_keychain(
      path: ENV["MATCH_KEYCHAIN_NAME"],
      add_to_search_list: :replace,
      password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )
#    match(
#      app_identifier: "jp.ivan.SwadeshNessMobile",
#      type: "development",
#      force_for_new_devices: false, # update only forced on non-CI systems, and only if there is a new device
#      # clone_branch_directly: true,
#      readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
#      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
#      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
#    )

    gym(
      scheme: "SwadeshNessMobile",
      clean: true,
      project: "./SwadeshNessMobile.xcodeproj",
      workspace: "./SwadeshNessMobile.xcworkspace", # since using pods
      export_method: "development",
    )

    #scan(
    #  scheme: "SwadeshNessMobile"
    #)
  end

end
